// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a manual implementation based on agent.proto

package proto

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// HealthCheckConfig represents health check configuration
type HealthCheckConfig struct {
	Path     string
	Interval int32
	Timeout  int32
	Retries  int32
}

// CreateContainerRequest represents a request to create a container
// JSON tags align with the agent's field names for wire compatibility.
type CreateContainerRequest struct {
	Image       string            `json:"ImageName"`
	Name        string            `json:"Name"`
	Port        int32             `json:"Port"`
	Environment map[string]string `json:"EnvVars"`
	CpuLimit    int64             `json:"CpuLimit"`
	MemoryLimit int64             `json:"MemLimit"`
	HealthCheck *HealthCheckConfig `json:"HealthCheck,omitempty"`
	Labels      map[string]string `json:"Labels"`
}

// CreateContainerResponse represents the response from creating a container
// JSON tags align with the agent's field names for wire compatibility.
type CreateContainerResponse struct {
	Success     bool   `json:"Success"`
	ContainerId string `json:"ContainerId"`
	InternalIp  string `json:"InternalIp"`
	HostPort    int32  `json:"HostPort"`
	Error       string `json:"Error"`
}

// RemoveContainerRequest represents a request to remove a container
type RemoveContainerRequest struct {
	ContainerId string
	Force       bool
}

// RemoveContainerResponse represents the response from removing a container
type RemoveContainerResponse struct {
	Success bool
}

// StartContainerRequest represents a request to start a container
type StartContainerRequest struct {
	ContainerId string
}

// StartContainerResponse represents the response from starting a container
type StartContainerResponse struct {
	Success bool
}

// StopContainerRequest represents a request to stop a container
type StopContainerRequest struct {
	ContainerId    string
	TimeoutSeconds int32
}

// StopContainerResponse represents the response from stopping a container
type StopContainerResponse struct {
	Success bool
}

// RestartContainerRequest represents a request to restart a container
type RestartContainerRequest struct {
	ContainerId    string
	TimeoutSeconds int32
}

// RestartContainerResponse represents the response from restarting a container
type RestartContainerResponse struct {
	Success bool
}

// GetLogsRequest represents a request to get container logs
type GetLogsRequest struct {
	ContainerId string
	Lines       int32
	Follow      bool
	Since       int64
}

// LogLine represents a single log line
type LogLine struct {
	Content   string
	Timestamp int64
}

// HealthCheckRequest represents a request to check container health
type HealthCheckRequest struct {
	ContainerId string
}

// HealthCheckResponse represents the response from a health check
type HealthCheckResponse struct {
	IsHealthy    bool
	Status       string
	CpuUsage     float64
	MemoryUsage  float64
	RestartCount int32
}

// ServerStatsRequest represents a request for server statistics
type ServerStatsRequest struct{}

// ServerStatsResponse represents server statistics
type ServerStatsResponse struct {
	CpuUsage       float64
	MemoryUsage    int64
	MemoryTotal    int64
	DiskUsage      int64
	DiskTotal      int64
	ContainerCount int32
}

// ContainerStatsRequest represents a request for container statistics
type ContainerStatsRequest struct {
	ContainerId string
}

// ContainerStatsResponse represents container statistics
type ContainerStatsResponse struct {
	ContainerId    string
	Status         string
	Health         string
	CpuPercent     float64
	MemoryUsage    int64
	MemoryLimit    int64
	MemoryPercent  float64
	NetworkRxBytes int64
	NetworkTxBytes int64
	BlockRead      int64
	BlockWrite     int64
	Pids           int64
	RestartCount   int32
	StartedAt      int64 // Unix timestamp
}

// PullImageRequest represents a request to pull an image
type PullImageRequest struct {
	Image        string `json:"ImageName"`
	RegistryAuth string `json:"RegistryAuth"`
}

// PullImageResponse represents the response from pulling an image
type PullImageResponse struct {
	Success bool
	Digest  string
}

// BuildImageRequest represents a request to build an image
type BuildImageRequest struct {
	ContextPath string
	Dockerfile  string
	Tag         string
	BuildArgs   map[string]string
	NoCache     bool
}

// BuildOutput represents build output
type BuildOutput struct {
	Stream  string
	Error   string
	IsError bool
}

// AgentServiceClient is the client API for AgentService
type AgentServiceClient interface {
	CreateContainer(ctx context.Context, in *CreateContainerRequest, opts ...grpc.CallOption) (*CreateContainerResponse, error)
	RemoveContainer(ctx context.Context, in *RemoveContainerRequest, opts ...grpc.CallOption) (*RemoveContainerResponse, error)
	StartContainer(ctx context.Context, in *StartContainerRequest, opts ...grpc.CallOption) (*StartContainerResponse, error)
	StopContainer(ctx context.Context, in *StopContainerRequest, opts ...grpc.CallOption) (*StopContainerResponse, error)
	RestartContainer(ctx context.Context, in *RestartContainerRequest, opts ...grpc.CallOption) (*RestartContainerResponse, error)
	GetContainerLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (AgentService_GetContainerLogsClient, error)
	CheckHealth(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	GetServerStats(ctx context.Context, in *ServerStatsRequest, opts ...grpc.CallOption) (*ServerStatsResponse, error)
	GetContainerStats(ctx context.Context, in *ContainerStatsRequest, opts ...grpc.CallOption) (*ContainerStatsResponse, error)
	PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (*PullImageResponse, error)
	BuildImage(ctx context.Context, in *BuildImageRequest, opts ...grpc.CallOption) (AgentService_BuildImageClient, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewAgentServiceClient creates a new AgentServiceClient
func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) CreateContainer(ctx context.Context, in *CreateContainerRequest, opts ...grpc.CallOption) (*CreateContainerResponse, error) {
	out := new(CreateContainerResponse)
	err := c.cc.Invoke(ctx, "/agent.AgentService/CreateContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RemoveContainer(ctx context.Context, in *RemoveContainerRequest, opts ...grpc.CallOption) (*RemoveContainerResponse, error) {
	out := new(RemoveContainerResponse)
	err := c.cc.Invoke(ctx, "/agent.AgentService/RemoveContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StartContainer(ctx context.Context, in *StartContainerRequest, opts ...grpc.CallOption) (*StartContainerResponse, error) {
	out := new(StartContainerResponse)
	err := c.cc.Invoke(ctx, "/agent.AgentService/StartContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StopContainer(ctx context.Context, in *StopContainerRequest, opts ...grpc.CallOption) (*StopContainerResponse, error) {
	out := new(StopContainerResponse)
	err := c.cc.Invoke(ctx, "/agent.AgentService/StopContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RestartContainer(ctx context.Context, in *RestartContainerRequest, opts ...grpc.CallOption) (*RestartContainerResponse, error) {
	out := new(RestartContainerResponse)
	err := c.cc.Invoke(ctx, "/agent.AgentService/RestartContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentService_GetContainerLogsClient is the client stream for GetContainerLogs
type AgentService_GetContainerLogsClient interface {
	Recv() (*LogLine, error)
	grpc.ClientStream
}

type agentServiceGetContainerLogsClient struct {
	grpc.ClientStream
}

func (x *agentServiceGetContainerLogsClient) Recv() (*LogLine, error) {
	m := new(LogLine)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agentServiceClient) GetContainerLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (AgentService_GetContainerLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, agentServiceGetContainerLogsStreamDesc, "/agent.AgentService/GetContainerLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceGetContainerLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

var agentServiceGetContainerLogsStreamDesc = &grpc.StreamDesc{
	StreamName:    "GetContainerLogs",
	ServerStreams: true,
}

func (c *agentServiceClient) CheckHealth(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/agent.AgentService/CheckHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetServerStats(ctx context.Context, in *ServerStatsRequest, opts ...grpc.CallOption) (*ServerStatsResponse, error) {
	out := new(ServerStatsResponse)
	err := c.cc.Invoke(ctx, "/agent.AgentService/GetServerStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetContainerStats(ctx context.Context, in *ContainerStatsRequest, opts ...grpc.CallOption) (*ContainerStatsResponse, error) {
	out := new(ContainerStatsResponse)
	err := c.cc.Invoke(ctx, "/agent.AgentService/GetContainerStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (*PullImageResponse, error) {
	out := new(PullImageResponse)
	err := c.cc.Invoke(ctx, "/agent.AgentService/PullImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentService_BuildImageClient is the client stream for BuildImage
type AgentService_BuildImageClient interface {
	Recv() (*BuildOutput, error)
	grpc.ClientStream
}

type agentServiceBuildImageClient struct {
	grpc.ClientStream
}

func (x *agentServiceBuildImageClient) Recv() (*BuildOutput, error) {
	m := new(BuildOutput)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agentServiceClient) BuildImage(ctx context.Context, in *BuildImageRequest, opts ...grpc.CallOption) (AgentService_BuildImageClient, error) {
	stream, err := c.cc.NewStream(ctx, agentServiceBuildImageStreamDesc, "/agent.AgentService/BuildImage", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceBuildImageClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

var agentServiceBuildImageStreamDesc = &grpc.StreamDesc{
	StreamName:    "BuildImage",
	ServerStreams: true,
}

// AgentServiceServer is the server API for AgentService
type AgentServiceServer interface {
	CreateContainer(context.Context, *CreateContainerRequest) (*CreateContainerResponse, error)
	RemoveContainer(context.Context, *RemoveContainerRequest) (*RemoveContainerResponse, error)
	StartContainer(context.Context, *StartContainerRequest) (*StartContainerResponse, error)
	StopContainer(context.Context, *StopContainerRequest) (*StopContainerResponse, error)
	RestartContainer(context.Context, *RestartContainerRequest) (*RestartContainerResponse, error)
	GetContainerLogs(*GetLogsRequest, AgentService_GetContainerLogsServer) error
	CheckHealth(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	GetServerStats(context.Context, *ServerStatsRequest) (*ServerStatsResponse, error)
	PullImage(context.Context, *PullImageRequest) (*PullImageResponse, error)
	BuildImage(*BuildImageRequest, AgentService_BuildImageServer) error
}

// AgentService_GetContainerLogsServer is the server stream for GetContainerLogs
type AgentService_GetContainerLogsServer interface {
	Send(*LogLine) error
	grpc.ServerStream
}

// AgentService_BuildImageServer is the server stream for BuildImage
type AgentService_BuildImageServer interface {
	Send(*BuildOutput) error
	grpc.ServerStream
}

// UnimplementedAgentServiceServer can be embedded to have forward compatible implementations
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) CreateContainer(context.Context, *CreateContainerRequest) (*CreateContainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateContainer not implemented")
}

func (UnimplementedAgentServiceServer) RemoveContainer(context.Context, *RemoveContainerRequest) (*RemoveContainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveContainer not implemented")
}

func (UnimplementedAgentServiceServer) StartContainer(context.Context, *StartContainerRequest) (*StartContainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartContainer not implemented")
}

func (UnimplementedAgentServiceServer) StopContainer(context.Context, *StopContainerRequest) (*StopContainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopContainer not implemented")
}

func (UnimplementedAgentServiceServer) RestartContainer(context.Context, *RestartContainerRequest) (*RestartContainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartContainer not implemented")
}

func (UnimplementedAgentServiceServer) GetContainerLogs(*GetLogsRequest, AgentService_GetContainerLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetContainerLogs not implemented")
}

func (UnimplementedAgentServiceServer) CheckHealth(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckHealth not implemented")
}

func (UnimplementedAgentServiceServer) GetServerStats(context.Context, *ServerStatsRequest) (*ServerStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerStats not implemented")
}

func (UnimplementedAgentServiceServer) PullImage(context.Context, *PullImageRequest) (*PullImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullImage not implemented")
}

func (UnimplementedAgentServiceServer) BuildImage(*BuildImageRequest, AgentService_BuildImageServer) error {
	return status.Errorf(codes.Unimplemented, "method BuildImage not implemented")
}

// RegisterAgentServiceServer registers the AgentServiceServer with the grpc.Server
func RegisterAgentServiceServer(s *grpc.Server, srv AgentServiceServer) {
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

// AgentService_ServiceDesc is the service descriptor for AgentService
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateContainer",
			Handler:    _AgentService_CreateContainer_Handler,
		},
		{
			MethodName: "RemoveContainer",
			Handler:    _AgentService_RemoveContainer_Handler,
		},
		{
			MethodName: "StartContainer",
			Handler:    _AgentService_StartContainer_Handler,
		},
		{
			MethodName: "StopContainer",
			Handler:    _AgentService_StopContainer_Handler,
		},
		{
			MethodName: "RestartContainer",
			Handler:    _AgentService_RestartContainer_Handler,
		},
		{
			MethodName: "CheckHealth",
			Handler:    _AgentService_CheckHealth_Handler,
		},
		{
			MethodName: "GetServerStats",
			Handler:    _AgentService_GetServerStats_Handler,
		},
		{
			MethodName: "PullImage",
			Handler:    _AgentService_PullImage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetContainerLogs",
			Handler:       _AgentService_GetContainerLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BuildImage",
			Handler:       _AgentService_BuildImage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent.proto",
}

func _AgentService_CreateContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CreateContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.AgentService/CreateContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CreateContainer(ctx, req.(*CreateContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RemoveContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RemoveContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.AgentService/RemoveContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RemoveContainer(ctx, req.(*RemoveContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StartContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StartContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.AgentService/StartContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StartContainer(ctx, req.(*StartContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StopContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StopContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.AgentService/StopContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StopContainer(ctx, req.(*StopContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RestartContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RestartContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.AgentService/RestartContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RestartContainer(ctx, req.(*RestartContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetContainerLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).GetContainerLogs(m, &agentServiceGetContainerLogsServer{stream})
}

type agentServiceGetContainerLogsServer struct {
	grpc.ServerStream
}

func (x *agentServiceGetContainerLogsServer) Send(m *LogLine) error {
	return x.ServerStream.SendMsg(m)
}

func _AgentService_CheckHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CheckHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.AgentService/CheckHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CheckHealth(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetServerStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetServerStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.AgentService/GetServerStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetServerStats(ctx, req.(*ServerStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_PullImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).PullImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.AgentService/PullImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).PullImage(ctx, req.(*PullImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_BuildImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuildImageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).BuildImage(m, &agentServiceBuildImageServer{stream})
}

type agentServiceBuildImageServer struct {
	grpc.ServerStream
}

func (x *agentServiceBuildImageServer) Send(m *BuildOutput) error {
	return x.ServerStream.SendMsg(m)
}
