version: '3.8'

services:
  traefik:
    image: traefik:v3.0
    container_name: easydeploy-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic:/etc/traefik/dynamic
      - ./acme:/etc/traefik/acme
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - easydeploy-network
    environment:
      - TZ=America/Sao_Paulo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.easyti.cloud`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_AUTH:-admin:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/}"

networks:
  easydeploy-network:
    driver: overlay
    attachable: true
