# EasyDeploy - Traefik dynamic routes
# Uses Go templates to read env vars from the Traefik container
http:
  routers:
    reverb:
      rule: "Host(`{{ env "PANEL_DOMAIN" }}`) && (PathPrefix(`/app`) || PathPrefix(`/apps`))"
      entryPoints:
        - websecure
      service: reverb
      priority: 100
      tls:
        certResolver: letsencrypt
    panel:
      rule: "Host(`{{ env "PANEL_DOMAIN" }}`)"
      entryPoints:
        - websecure
      service: panel
      tls:
        certResolver: letsencrypt
    orchestrator:
      rule: "Host(`{{ env "API_DOMAIN" }}`)"
      entryPoints:
        - websecure
      service: orchestrator
      tls:
        certResolver: letsencrypt
{{ if env "TRAEFIK_DASHBOARD_DOMAIN" }}
    dashboard:
      rule: "Host(`{{ env "TRAEFIK_DASHBOARD_DOMAIN" }}`)"
      entryPoints:
        - websecure
      service: api@internal
      middlewares:
        - dashboard-auth
      tls:
        certResolver: letsencrypt
{{ end }}
  services:
    panel:
      loadBalancer:
        servers:
          - url: "http://easydeploy-panel:8000"
    reverb:
      loadBalancer:
        servers:
          - url: "http://easydeploy-reverb:9000"
    orchestrator:
      loadBalancer:
        servers:
          - url: "http://easydeploy-orchestrator:8080"
{{ if env "TRAEFIK_AUTH" }}
  middlewares:
    dashboard-auth:
      basicAuth:
        users:
          - "{{ env "TRAEFIK_AUTH" }}"
{{ end }}
